let QUESTIONS = [
  // Previous 20 questions (from last response) remain, adding 50 more
  { q: "What is the standard pupillary distance range for adults?", o: ["50-70 mm", "30-50 mm", "70-90 mm", "40-60 mm"], a: 0, c: "Lens Basics", e: "Pupillary distance (PD) typically ranges from 50 to 70 mm for adults." },
  { q: "Which frame material is known for being hypoallergenic?", o: ["Plastic", "Titanium", "Aluminum", "Wood"], a: 1, c: "Frame Fitting", e: "Titanium is hypoallergenic due to its resistance to corrosion." },
  { q: "What should you do if a patient complains of discomfort?", o: ["Ignore it", "Adjust the frame", "Replace lenses", "Refer to optometrist"], a: 1, c: "Patient Care", e: "Adjusting the frame can resolve discomfort; refer if needed." },
  { q: "What is the primary use of prism in eyeglasses?", o: ["Correct color blindness", "Align misaligned eyes", "Increase magnification", "Reduce glare"], a: 1, c: "Prisms", e: "Prisms shift images to correct binocular vision issues." },
  { q: "How is prism power measured?", o: ["In diopters", "In prism diopters", "In millimeters", "In degrees"], a: 1, c: "Prisms", e: "Prism power is measured in prism diopters." },
  { q: "What does 'base' direction indicate in a prism?", o: ["Lens thickness", "Image shift direction", "Frame size", "Lens material"], a: 1, c: "Prisms", e: "Base direction shows where the prism apex points." },
  { q: "What is the primary function of a lensometer?", o: ["Measure eye pressure", "Verify lens power", "Adjust frames", "Test color vision"], a: 1, c: "Instrumentation", e: "A lensometer measures lens prescription power." },
  { q: "Which instrument measures pupillary distance?", o: ["Lensometer", "Pupillometer", "Keratomter", "Tonometer"], a: 1, c: "Instrumentation", e: "A pupillometer measures PD for lens fitting." },
  { q: "What part of the eye refracts light to the retina?", o: ["Cornea", "Iris", "Lens", "Sclera"], a: 2, c: "Anatomy and Physiology", e: "The lens refracts light onto the retina." },
  { q: "What is the retina's function?", o: ["Protect the eye", "Detect light", "Produce tears", "Regulate pupil"], a: 1, c: "Anatomy and Physiology", e: "The retina detects light and sends signals to the brain." },
  { q: "Which condition involves lens clouding?", o: ["Glaucoma", "Cataract", "Macular degeneration", "Retinal detachment"], a: 1, c: "Ocular Pathology", e: "A cataract clouds the lens, blurring vision." },
  { q: "What is a glaucoma symptom?", o: ["Double vision", "Increased eye pressure", "Color blindness", "Dry eyes"], a: 1, c: "Ocular Pathology", e: "Glaucoma increases intraocular pressure." },
  { q: "What law requires patient privacy?", o: ["OSHA", "HIPAA", "ADA", "FDA"], a: 1, c: "Legislation and Regulation", e: "HIPAA protects patient health information." },
  { q: "Who regulates eyeglass dispensing?", o: ["FDA", "State boards", "AMA", "CDC"], a: 1, c: "Legislation and Regulation", e: "State boards regulate opticianry." },
  { q: "What lens corrects nearsightedness?", o: ["Convex", "Concave", "Bifocal", "Prism"], a: 1, c: "Lens Basics", e: "Concave lenses correct myopia." },
  { q: "Which tool bends temples?", o: ["Screwdriver", "Pliers", "Heat gun", "Lens clock"], a: 2, c: "Frame Fitting", e: "A heat gun softens frames for adjustments." },
  { q: "What to check if a prescription seems wrong?", o: ["Frame size", "Lens thickness", "Prescription", "Patient age"], a: 2, c: "Patient Care", e: "Verify the prescription for accuracy." },
  { q: "What aberration causes starburst effects?", o: ["Coma", "Spherical", "Chromatic", "Astigmatism"], a: 0, c: "Ophthalmic Optics", e: "Coma causes starburst effects around lights." },
  { q: "How often should a lensometer be calibrated?", o: ["Daily", "Weekly", "Monthly", "Annually"], a: 0, c: "Instrumentation", e: "Daily calibration ensures accuracy." },
  { q: "Which muscle controls pupil size?", o: ["Ciliary", "Iris sphincter", "Rectus", "Oblique"], a: 1, c: "Anatomy and Physiology", e: "The iris sphincter constricts the pupil." },
  // New 50 Questions
  { q: "Calculate the total prism power if one lens has 2Δ base out and the other has 1.5Δ base in.", o: ["0.5Δ", "3.5Δ", "1.5Δ", "2Δ"], a: 0, c: "Prisms", e: "Prism power subtracts when bases oppose: 2 - 1.5 = 0.5Δ." },
  { q: "What is the focal length of a +4.00D lens?", o: ["0.25m", "0.5m", "1m", "4m"], a: 0, c: "Lens Basics", e: "Focal length = 1/D = 1/4 = 0.25m." },
  { q: "Which lens material has the highest index of refraction?", o: ["CR-39", "Polycarbonate", "Trivex", "High-index 1.74"], a: 3, c: "Lens Basics", e: "High-index 1.74 has the highest refraction index." },
  { q: "What angle should temple tips be adjusted to?", o: ["90°", "95°-100°", "85°", "110°"], a: 1, c: "Frame Fitting", e: "95°-100° ensures a secure fit behind the ear." },
  { q: "How many millimeters is a typical lens decentration?", o: ["1-2mm", "5-10mm", "15-20mm", "25mm"], a: 0, c: "Patient Care", e: "Decentration is usually 1-2mm for PD adjustments." },
  { q: "What is the Prentice Rule formula?", o: ["P = h × F", "P = F / h", "P = h + F", "P = F - h"], a: 0, c: "Ophthalmic Optics", e: "Prism power (P) = height (h) × lens power (F)." },
  { q: "Which instrument measures corneal curvature?", o: ["Lensometer", "Keratometer", "Pupillometer", "Tonometer"], a: 1, c: "Instrumentation", e: "A keratometer measures corneal curvature." },
  { q: "What nerve transmits visual signals?", o: ["Optic", "Oculomotor", "Trochlear", "Abducens"], a: 0, c: "Anatomy and Physiology", e: "The optic nerve carries visual information to the brain." },
  { q: "Which condition causes tunnel vision?", o: ["Cataract", "Glaucoma", "Macular degeneration", "Retinitis pigmentosa"], a: 1, c: "Ocular Pathology", e: "Glaucoma can lead to peripheral vision loss." },
  { q: "What is the minimum age to dispense glasses without supervision?", o: ["18", "21", "25", "30"], a: 1, c: "Legislation and Regulation", e: "Age 21 is often required, varying by state." },
  { q: "Calculate the vertex compensation for a -6.00D lens at 12mm.", o: ["-0.41D", "-0.82D", "-1.23D", "-1.64D"], a: 1, c: "Lens Basics", e: "Compensation = F² × d = (-6)² × 0.012 = 0.432D, approx -0.82D." },
  { q: "Which frame part connects lenses to temples?", o: ["Bridge", "Endpiece", "Rim", "Pad arm"], a: 1, c: "Frame Fitting", e: "The endpiece links lenses to temples." },
  { q: "What to do if a patient has a red eye?", o: ["Fit new glasses", "Refer to a doctor", "Adjust frame", "Clean lenses"], a: 1, c: "Patient Care", e: "Red eye may indicate infection; refer to a doctor." },
  { q: "What causes chromatic aberration?", o: ["Lens thickness", "Light dispersion", "Frame weight", "Pupil size"], a: 1, c: "Ophthalmic Optics", e: "Chromatic aberration results from light splitting into colors." },
  { q: "How to clean a lensometer?", o: ["Water", "Alcohol wipes", "Soap", "Compressed air"], a: 1, c: "Instrumentation", e: "Alcohol wipes safely clean lensometer lenses." },
  { q: "What protects the cornea?", o: ["Conjunctiva", "Sclera", "Retina", "Choroid"], a: 0, c: "Anatomy and Physiology", e: "The conjunctiva covers and protects the cornea." },
  { q: "Which condition causes floaters?", o: ["Cataract", "Retinal detachment", "Glaucoma", "Keratitis"], a: 1, c: "Ocular Pathology", e: "Retinal detachment can cause floaters or flashes." },
  { q: "What requires a written prescription?", o: ["Sunglasses", "Reading glasses", "Contact lenses", "Safety glasses"], a: 2, c: "Legislation and Regulation", e: "Contact lenses require a valid prescription." },
  { q: "What is the power of a lens with 25cm focal length?", o: ["+4.00D", "+2.00D", "+0.25D", "-4.00D"], a: 0, c: "Lens Basics", e: "Power = 1/f = 1/0.25 = +4.00D." },
  { q: "Which adjustment fixes a loose frame?", o: ["Tighten screws", "Widen bridge", "Lower temples", "Increase PD"], a: 0, c: "Frame Fitting", e: "Tightening screws stabilizes a loose frame." },
  { q: "What to check for lens scratches?", o: ["Frame fit", "Lens coating", "Pupil size", "Bridge width"], a: 1, c: "Patient Care", e: "Lens coatings can show scratches affecting vision." },
  { q: "What is the angle of a pantoscopic tilt?", o: ["5°-15°", "20°-30°", "45°", "90°"], a: 0, c: "Ophthalmic Optics", e: "Pantoscopic tilt is typically 5°-15° for comfort." },
  { q: "Which tool measures lens thickness?", o: ["Calipers", "Lens clock", "Pupillometer", "Tonometer"], a: 0, c: "Instrumentation", e: "Calipers measure lens edge thickness." },
  { q: "What muscle moves the eye upward?", o: ["Superior rectus", "Inferior oblique", "Lateral rectus", "Medial rectus"], a: 0, c: "Anatomy and Physiology", e: "The superior rectus elevates the eye." },
  { q: "Which condition blurs near vision?", o: ["Presbyopia", "Myopia", "Hyperopia", "Astigmatism"], a: 0, c: "Ocular Pathology", e: "Presbyopia affects near focusing with age." },
  { q: "What is a CE mark on frames?", o: ["Color enhancement", "European standard", "Custom engraving", "Corrosion evidence"], a: 1, c: "Legislation and Regulation", e: "CE marks indicate compliance with EU safety standards." },
  { q: "Calculate prism induced by 4D lens decentered 5mm.", o: ["10Δ", "20Δ", "5Δ", "2Δ"], a: 1, c: "Prisms", e: "Prism = F × c = 4 × 5 = 20Δ." },
  { q: "Which lens reduces eye strain?", o: ["Photochromic", "Polarized", "Anti-reflective", "Tinted"], a: 2, c: "Lens Basics", e: "Anti-reflective coatings reduce glare and strain." },
  { q: "What fixes a frame slipping down?", o: ["Widen temples", "Tighten bridge", "Lower pads", "Increase weight"], a: 2, c: "Frame Fitting", e: "Lowering nose pads prevents slipping." },
  { q: "What to do if a lens pops out?", o: ["Use superglue", "Reinsert and adjust", "Replace frame", "Ignore it"], a: 1, c: "Patient Care", e: "Reinsert and adjust the lens properly." },
  { q: "What causes spherical aberration?", o: ["Uneven curvature", "Light reflection", "Lens color", "Frame shape"], a: 0, c: "Ophthalmic Optics", e: "Spherical aberration results from uneven lens curvature." },
  { q: "How to test lensometer accuracy?", o: ["Use known lens", "Check frame", "Measure PD", "Adjust screws"], a: 0, c: "Instrumentation", e: "A known lens verifies lensometer accuracy." },
  { q: "What supplies aqueous humor?", o: ["Ciliary body", "Cornea", "Retina", "Iris"], a: 0, c: "Anatomy and Physiology", e: "The ciliary body produces aqueous humor." },
  { q: "Which condition causes night blindness?", o: ["Cataract", "Retinitis pigmentosa", "Glaucoma", "Macular degeneration"], a: 1, c: "Ocular Pathology", e: "Retinitis pigmentosa affects night vision." },
  { q: "What law governs workplace safety?", o: ["HIPAA", "OSHA", "ADA", "FDA"], a: 1, c: "Legislation and Regulation", e: "OSHA ensures safe working conditions." },
  { q: "What is the power of a -2.50D lens at 10mm vertex?", o: ["-2.45D", "-2.55D", "-2.60D", "-2.50D"], a: 0, c: "Lens Basics", e: "Compensation = F² × d = (-2.5)² × 0.01 = 0.0625D, approx -2.45D." },
  { q: "Which frame style suits a round face?", o: ["Round", "Rectangular", "Oval", "Square"], a: 1, c: "Frame Fitting", e: "Rectangular frames balance a round face." },
  { q: "What to do if a patient sees double?", o: ["Adjust frame", "Check prism", "Clean lenses", "Refer to doctor"], a: 1, c: "Patient Care", e: "Double vision may need prism correction." },
  { q: "What is the minimum PD for bifocals?", o: ["45mm", "50mm", "55mm", "60mm"], a: 1, c: "Ophthalmic Optics", e: "50mm is a typical minimum PD for bifocals." },
  { q: "Which tool aligns lens markings?", o: ["Lens clock", "Pupillometer", "Keratometer", "Tonometer"], a: 0, c: "Instrumentation", e: "A lens clock aligns cylinder axis markings." },
  { q: "What vein drains the retina?", o: ["Central retinal vein", "Pulmonary vein", "Jugular vein", "Corneal vein"], a: 0, c: "Anatomy and Physiology", e: "The central retinal vein drains retinal blood." },
  { q: "Which condition causes sudden vision loss?", o: ["Cataract", "Retinal detachment", "Presbyopia", "Hyperopia"], a: 1, c: "Ocular Pathology", e: "Retinal detachment can cause sudden vision loss." },
  { q: "What requires a dispensing license?", o: ["Sunglasses", "Prescription glasses", "Safety goggles", "Reading glasses"], a: 1, c: "Legislation and Regulation", e: "Prescription glasses require a license." },
  { q: "Calculate the effective power of +3.00D at 5mm vertex.", o: ["+2.93D", "+3.07D", "+3.00D", "+3.15D"], a: 0, c: "Lens Basics", e: "Compensation = F² × d = (3)² × 0.005 = 0.045D, approx +2.93D." },
  { q: "Which frame part supports the nose?", o: ["Bridge", "Temples", "Endpiece", "Rim"], a: 0, c: "Frame Fitting", e: "The bridge supports the nose." },
  { q: "What to do if a frame breaks?", o: ["Use tape", "Replace it", "Adjust screws", "Clean it"], a: 1, c: "Patient Care", e: "A broken frame should be replaced." },
  { q: "What is the effect of a +1.00D lens decentered 2cm?", o: ["2Δ", "1Δ", "0.5Δ", "4Δ"], a: 0, c: "Ophthalmic Optics", e: "Prism = F × c = 1 × 2 = 2Δ." },
  { q: "How to maintain a pupillometer?", o: ["Lubricate", "Clean lens", "Tighten screws", "Replace battery"], a: 1, c: "Instrumentation", e: "Cleaning the lens ensures accurate PD measurement." },
  { q: "What gland produces tears?", o: ["Lacrimal", "Pituitary", "Thyroid", "Adrenal"], a: 0, c: "Anatomy and Physiology", e: "The lacrimal gland produces tears." },
  { q: "Which condition causes light sensitivity?", o: ["Glaucoma", "Photophobia", "Cataract", "Macular degeneration"], a: 1, c: "Ocular Pathology", e: "Photophobia is sensitivity to light." },
  { q: "What is a common optician certification?", o: ["CPA", "ABO", "RN", "MD"], a: 1, c: "Legislation and Regulation", e: "ABO certification is standard for opticians." }
];

const CATEGORIES = [...new Set(QUESTIONS.map(q => q.c))];